masteriesData = [
	{ id: "m0",
	  max: 1,
	  title: "Double-Edged Sword",
	  description: "",
	  invis: false
    },
    { id: "m1",
	  max: 4,
	  title: "Fury",
	  description: "",
	  invis: false
    },
    { id: "m2",
	  max: 4,
	  title: "Sorcery",
	  description: "",
	  invis: false
    },
    { id: "m3",
	  max: 1,
	  title: "Butcher",
	  description: "",
	  invis: false
    },    
    { id: "m4",
	  max: 1,
	  title: "Expose Weakness",
	  description: "",
	  invis: false
    },
    { id: "m5",
	  max: 3,
	  title: "Brute Force",
	  description: "",
	  invis: false
    },
    { id: "m6",
	  max: 3,
	  title: "Mental Force",
	  description: "",
	  invis: false
    },
    { id: "m7",
	  max: 1,
	  title: "Feast",
	  description: "",
	  dependency: "m3",
	  invis: false
    },
    { id: "m8",
	  max: 1,
	  title: "Spell Weaving",
	  description: "",
	  invis: false
    },
    { id: "m9",
	  max: 1,
	  title: "Martial Mastery",
	  description: "",
	  dependency: "m5",
	  invis: false
    },
    { id: "m10",
	  max: 1,
	  title: "Arcane Mastery",
	  description: "",
	  dependency: "m6",
	  invis: false
    },
    { id: "m11",
	  max: 3,
	  title: "Executioner",
	  description: "",
	  invis: false
    },
    { id: "m12",
	  max: 1,
	  title: "Blade Weaving",
	  description: "",
	  dependency: "m8",
	  invis: false
    },
    { id: "m13",
	  max: 3,
	  title: "Warlord",
	  description: "",
	  invis: false
    },
    { id: "m14",
	  max: 3,
	  title: "Archmage",
	  description: "",
	  invis: false
    },
    { id: "m15",
	  max: 1,
	  title: "Dangerous Game",
	  description: "",
	  dependency: "m11",
	  invis: false
    },
    { id: "m16",
	  max: 1,
	  title: "Frenzy",
	  description: "",
	  invis: false
    },
    { id: "m17",
	  max: 3,
	  title: "Devastating Strikes",
	  description: "",
	  invis: false
    },
    { id: "m18",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m19",
	  max: 3,
	  title: "Devastating Strikes",
	  description: "",
	  invis: false
    },
    { id: "m20",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m21",
	  max: 1,
	  title: "Havoc",
	  description: "",
	  invis: false
    },
    { id: "m22",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m23",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m24",
	  max: 2,
	  title: "Block",
	  description: "",
	  invis: false
    },
    { id: "m25",
	  max: 2,
	  title: "Recovery",
	  description: "",
	  invis: false
    },
    { id: "m26",
	  max: 2,
	  title: "Enchanted Armor",
	  description: "",
	  invis: false
    },
    { id: "m27",
	  max: 2,
	  title: "Tough Skin",
	  description: "",
	  invis: false
    },
    { id: "m28",
	  max: 1,
	  title: "Unyielding",
	  description: "",
	  invis: false
    },
    { id: "m29",
	  max: 3,
	  title: "Veteran's Scars",
	  description: "",
	  invis: false
    },
    { id: "m30",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m31",
	  max: 1,
	  title: "Bladed Armor",
	  description: "",
	  invis: false
    },
    { id: "m32",
	  max: 1,
	  title: "Oppression",
	  description: "",
	  invis: false
    },
    { id: "m33",
	  max: 1,
	  title: "Juggernaut",
	  description: "",
	  invis: false
    },
    { id: "m34",
	  max: 3,
	  title: "Hardiness",
	  description: "",
	  invis: false
    },
    { id: "m35",
	  max: 3,
	  title: "Resistance",
	  description: "",
	  invis: false
    },
    { id: "m36",
	  max: 3,
	  title: "Perserverance",
	  description: "",
	  invis: false
    },
    { id: "m37",
	  max: 1,
	  title: "Swiftness",
	  description: "",
	  invis: false
    },
    { id: "m38",
	  max: 1,
	  title: "Reinforced Amror",
	  description: "",
	  invis: false
    },
    { id: "m39",
	  max: 1,
	  title: "Evasive",
	  description: "",
	  invis: false
    },
    { id: "m40",
	  max: 1,
	  title: "Second Wind",
	  description: "",
	  invis: false
    },
    { id: "m41",
	  max: 4,
	  title: "Legendary Guardian",
	  description: "",
	  invis: false
    },
    { id: "m42",
	  max: 1,
	  title: "Runic Blessing",
	  description: "",
	  invis: false
    },
    { id: "m43",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m44",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m45",
	  max: 1,
	  title: "Tenacious",
	  description: "",
	  invis: false
    },
    { id: "m46",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m47",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m48",
	  max: 1,
	  title: "Phasewalker",
	  description: "",
	  invis: false
    },
    { id: "m49",
	  max: 3,
	  title: "Fleet of foot",
	  description: "",
	  invis: false
    },
    { id: "m50",
	  max: 3,
	  title: "Meditation",
	  description: "",
	  invis: false
    },
    { id: "m51",
	  max: 1,
	  title: "Scout",
	  description: "",
	  invis: false
    },
    { id: "m52",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m53",
	  max: 3,
	  title: "Summoner's Insight",
	  description: "",
	  invis: false
    },
    { id: "m54",
	  max: 1,
	  title: "Strength of Spirit",
	  description: "",
	  invis: false
    },
    { id: "m55",
	  max: 1,
	  title: "Alchemist",
	  description: "",
	  invis: false
    },
    { id: "m56",
	  max: 3,
	  title: "Greed",
	  description: "",
	  invis: false
    },
    { id: "m57",
	  max: 1,
	  title: "Runic Affinity",
	  description: "",
	  invis: false
    },
    { id: "m58",
	  max: 3,
	  title: "Vampirism",
	  description: "",
	  invis: false
    },
    { id: "m59",
	  max: 1,
	  title: "Culinary Master",
	  description: "",
	  invis: false
    },
    { id: "m60",
	  max: 1,
	  title: "Scavenger",
	  description: "",
	  invis: false
    },
    { id: "m61",
	  max: 1,
	  title: "Wealth",
	  description: "",
	  invis: true
	},
	{ id: "m62",
	  max: 3,
	  title: "Expanded Mind",
	  description: "",
	  invis: false
    },
    { id: "m63",
	  max: 2,
	  title: "Insipiration",
	  description: "",
	  invis: false
    },
    { id: "m64",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m65",
	  max: 1,
	  title: "Bandit",
	  description: "",
	  invis: false
    },
    { id: "m66",
	  max: 3,
	  title: "Intelligence",
	  description: "",
	  invis: false
	},
	{ id: "m67",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
	},
	{ id: "m68",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m69",
	  max: 1,
	  title: "Wanderer",
	  description: "",
	  invis: false
    },
    { id: "m70",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    },
    { id: "m71",
	  max: -1,
	  title: "",
	  description: "",
	  invis: true
    }
]